# Generated by Django 2.1.7 on 2019-03-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20190312_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
