# Generated by Django 2.1.7 on 2019-03-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20190312_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_added']},
        ),
    ]
